Back/Controllers/AccountController.cs
using Back.Helpers;
using Data.Context;
using Data.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Back.Controllers
{
    public class AccountController : Controller
    {
        private ParktrackContext db;
        public AccountController(ParktrackContext context)
        {
            db = context;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(User user)
        {
            if (user.Username != null && user.Password != null)
            {
                User validUser = null;
                // user.Password = HashHelper.GetMD5Hash(user.Password);
                // User validUser = db.User.FirstOrDefault(u => u.Username == user.Username && u.Password == user.Password);

                // temporal, comprobar credenciales en la base de datos
                if (user.Username == "innotu" && user.Password == "innotu")
                {
                    validUser = user;
                }

                if (validUser != null)
                {
                    var claims = new List<Claim>();
                    claims.Add(new Claim(ClaimTypes.Name, "User"));

                    claims.Add(new Claim(ClaimTypes.Role, "UserRole"));

                    // añadir claim de admin
                    if (validUser.Username == "innotu")
                    {
                        claims.Add(new Claim(ClaimTypes.Role, "AdminRole"));
                    }

                    var appIdentity = new ClaimsIdentity(claims);
                    HttpContext.User.AddIdentity(appIdentity);

                    var authProperties = new AuthenticationProperties
                    {
                        IsPersistent = true,

                        ExpiresUtc = DateTimeOffset.UtcNow.AddHours(12),
                        // The time at which the authentication ticket expires. A 
                        // value set here overrides the ExpireTimeSpan option of 
                        // CookieAuthenticationOptions set with AddCookie.

                        RedirectUri = "/login"
                        // The full path or absolute URI to be used as an http 
                        // redirect response value.
                    };

                    var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    claimsIdentity.Label = user.Id.ToString();

                    await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity), authProperties);    //authProperties

                    HttpContext.Session.SetInt32("id", validUser.Id);
                    HttpContext.Session.SetString("userId", validUser.Id.ToString());
                    HttpContext.Session.SetString("username", validUser.Username);

                    LanguageHelper.ChangeLanguage("es");

                    return Redirect("/");
                }
            }

            return RedirectToAction(nameof(Login), new { message = "usuario no valido" });
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Session.Clear();

            HttpContext.SignOutAsync();
            return RedirectToAction(nameof(Login), new { message = "logout" });

        }
    }
}

Back/Controllers/HomeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Back.Controllers
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Back/Controllers/IdiomasController.cs
using Back.Helpers;
using Data.Context;
using Data.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Headers;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Back.Controllers
{
    public class IdiomasController : Controller
    {
        private ParktrackContext db;
        public IdiomasController(ParktrackContext db)
        {
            this.db = db;
        }
        public IActionResult ChangeLanguage(string selectedLanguage)
        {
            if (selectedLanguage != null)
            {
                // buscar el idioma en la tabla de la base de datos
                //Language language = db.Language.FirstOrDefault(l => l.DescriptionToken == selectedLanguage);

                //Grabacion usuario
                //int idUsuario = Convert.ToInt32(HttpContext.Session.GetInt32("id"));
                //User usuario = db.User.FirstOrDefault(a => a.Id == idUsuario);
                //usuario.Language = language;
                //db.Update(usuario);
                //db.SaveChanges();

                LanguageHelper.ChangeLanguage(selectedLanguage);

                this.Response.Cookies.Append(CookieRequestCultureProvider.DefaultCookieName, CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(selectedLanguage)), new CookieOptions()
                {
                    Expires = DateTimeOffset.UtcNow.AddYears(1),
                });

            }

            RequestHeaders header = Request.GetTypedHeaders();
            Uri uriReferer = header.Referer;

            if (uriReferer != null)
            {
                //return RedirectToAction("Index", uriReferer.AbsolutePath);
                return Redirect(uriReferer.AbsoluteUri);
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

Back/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Data.Context;
using Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Back.Controllers
{
    public class UserController : Controller
    {
        private readonly ParktrackContext db;

        public UserController(ParktrackContext context)
        {
            db = context;
        }

        [Authorize(Policy = "Admin")]
        public async Task<IActionResult> Index()
        {
            return View(db.User.ToList());
        }

        public async Task<IActionResult> Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(User user)
        {
            try
            {
                db.User.Add(user);
                await db.SaveChangesAsync();
                return Ok();
            }
            catch
            {
                return BadRequest();
            }

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await db.User.FindAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            try
            {
                db.User.Update(user);
                await db.SaveChangesAsync();
                return Ok();
            }
            catch
            {
                return BadRequest();
            }
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await db.User
                .FirstOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return Ok(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var user = await db.User.FindAsync(id);
                db.User.Remove(user);
                await db.SaveChangesAsync();
                return Ok();
            }
            catch
            {
                return BadRequest();
            }
        }
    }
}

Back/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>


@section Scripts{ 
    <script>
        $("#menu-home").addClass("nav-active");
    </script>

}

Back/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

@{
    if (@HttpContextAccessor.HttpContext.Session.GetString("userId") == null)
    {
        Context.Response.Redirect(Url.Action("Login", "Account"));
    }
}
<!doctype html>
<html class="fixed sidebar-light" data-style-switcher-options="{'sidebarColor': 'light'}">
<head>

    <!-- Basic -->
    <meta charset="UTF-8">

    <title>Blank Project</title>
    <meta name="keywords" content="HTML5 Admin Template" />
    <meta name="description" content="BlankProject">
    <meta name="author" content="innotu.com">

    <!-- Mobile Metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />

    <!-- Web Fonts  -->
    @*<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">*@
    <link href="https://fonts.googleapis.com/css?family=Poppins:500,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">


    <!-- Vendor CSS -->
    <link rel="stylesheet" href="~/Scripts/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/animate/animate.compat.css">

    <link rel="stylesheet" href="~/Scripts/vendor/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/boxicons/css/boxicons.min.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/datatables/media/css/dataTables.bootstrap4.css" />

    <!-- Specific Page Vendor CSS -->
    <link rel="stylesheet" href="~/Scripts/vendor/jquery-ui/jquery-ui.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/jquery-ui/jquery-ui.theme.css" />

    
    <!-- Theme CSS -->
    <link rel="stylesheet" href="~/Scripts/css/theme.css" />

    
    <!-- Theme Custom CSS -->
    <link rel="stylesheet" href="~/Scripts/css/custom.css">


    <!-- Head Libs -->
    <script src="~/Scripts/vendor/modernizr/modernizr.js"></script>
    <script src="~/Scripts/master/style-switcher/style.switcher.localstorage.js"></script>


    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"
            integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
            crossorigin="anonymous"></script>

</head>
<body>
    <section class="body">

        <header class="header">

            <div class="logo-container d-inline">
                <a href="/" class="logo">
                    <img src="~/img/logo-innotu.png" alt="Airlan Tracker" width="120px">
                </a>
                <div class="d-md-none toggle-sidebar-left" data-toggle-class="sidebar-left-opened" data-target="html" data-fire-event="sidebar-left-opened">
                    <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
                </div>
                <span class="separator invisible"></span>
            </div>

            <!-- start: languages & user box -->
            <div class="header-right">
                <span class="separator"></span>
                <partial name="~/Views/Shared/_SelectorIdioma.cshtml" />

                <span class="separator"></span>

                <partial name="~/Views/Shared/_MenuUsuario.cshtml" />

            </div>
            <!-- end: search & user box -->
        </header>

        <div class="inner-wrapper">
            <!-- start: sidebar -->
            <partial name="~/Views/Shared/_MenuLateral.cshtml" />
            <!-- end: sidebar -->

            <section role="main" class="content-body">
                <header class="page-header">
                    <h2>@ViewData["Title"]</h2>
                </header>

                <!-- start: page -->
                @RenderBody()
                <!-- end: page -->
            </section>
        </div>


    </section>

    <!-- Vendor -->
    <script src="~/Scripts/vendor/jquery-browser-mobile/jquery.browser.mobile.js"></script>
    <script src="~/Scripts/vendor/jquery-cookie/jquery.cookie.js"></script>
    <script src="~/Scripts/vendor/popper/umd/popper.min.js"></script>
    <script src="~/Scripts/vendor/bootstrap/js/bootstrap.js"></script>
    <script src="~/Scripts/vendor/jquery-placeholder/jquery.placeholder.js"></script>

    <!-- Specific Page Vendor -->
    <script src="~/Scripts/vendor/jquery-ui/jquery-ui.js"></script>
    <script src="~/Scripts/vendor/jqueryui-touch-punch/jquery.ui.touch-punch.js"></script>
    <script src="~/Scripts/vendor/jquery-appear/jquery.appear.js"></script>
    <script src="~/Scripts/vendor/nanoscroller/nanoscroller.js"></script>

    <partial name="~/Views/Shared/_ValidationScriptsPartial.cshtml" />

    <script src="~/Scripts/js/custom.js" charset="utf-8"></script>

    @RenderSection("Scripts", required: false)

    <!-- Theme Base, Components and Settings -->
    <!-- Theme Initialization Files -->
    <script src="~/Scripts/js/theme.js"></script>
    <script src="~/Scripts/js/theme.init.js"></script>
</body>
</html>

Back/Views/Shared/_LayoutNonRegistered.cshtml
@{
    Layout = null;
}
<!doctype html>
<html class="fixed">
<head>
    <title>Airlan Tracker</title>
    <meta charset="UTF-8">
    <meta name="description" content="Airlan Tracker">
    <meta name="author" content="okler.net">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800|Shadows+Into+Light" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="~/Scripts/vendor/bootstrap/css/bootstrap.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/animate/animate.compat.css">

    <link rel="stylesheet" href="~/Scripts/vendor/font-awesome/css/all.min.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/boxicons/css/boxicons.min.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/magnific-popup/magnific-popup.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/bootstrap-datepicker/css/bootstrap-datepicker3.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/jquery-ui/jquery-ui.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/jquery-ui/jquery-ui.theme.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/bootstrap-multiselect/css/bootstrap-multiselect.css" />
    <link rel="stylesheet" href="~/Scripts/vendor/morris/morris.css" />
    <link rel="stylesheet" href="~/Scripts/css/theme.css" />

    <link rel="stylesheet" href="~/Scripts/css/custom.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="~/Scripts/vendor/modernizr/modernizr.js"></script>
    <script src="~/Scripts/master/style-switcher/style.switcher.localstorage.js"></script>

    @RenderSection("CSS", required: false)

</head>
<body>

    <section class="body-sign">
        <div class="center-sign">
            <a href="#" class="logo float-left">
                <img src="~/img/logo-innotu.png" height="40" alt="logo-innotu" />
            </a>

            <div class="panel card-sign">
                <div class="card-title-sign mt-3 text-right">
                    <h2 class="title text-uppercase font-weight-bold m-0"><i class="bx bx-user-circle mr-1 text-6 position-relative top-5"></i> Sign In</h2>
                </div>
                <div class="card-body">
                    @RenderBody()
                </div>
            </div>
        </div>
    </section>


</body>
</html>

<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script src="~/js/site.js"></script>
@RenderSection("Scripts", required: false)

Back/Views/Shared/_MenuLateral.cshtml
@using Microsoft.AspNetCore.Http
@model dynamic
@{
    Layout = null;
}

<aside id="sidebar-left" class="sidebar-left">

    <div class="sidebar-header">
        <div class="sidebar-title">
            <!--Navigation-->
        </div>
        <div class="sidebar-toggle d-none d-md-block" data-toggle-class="sidebar-left-collapsed" data-target="html" data-fire-event="sidebar-left-toggle">
            <i class="fas fa-bars" aria-label="Toggle sidebar"></i>
        </div>
    </div>

    <div class="nano">
        <div class="nano-content">
            <nav id="menu" class="nav-main" role="navigation">
                <ul class="nav nav-main">

                    <li id="menu-home">
                        <a class="nav-link" href="@Url.Action("Index", "Home")">
                            <i class="fas fa-home" aria-hidden="true"></i>
                            <span>@Back.Resources.Menu.Resource.Home</span>
                        </a>
                    </li>

                    <li class="nav-parent" id="menu-administration">
                        <a class="nav-link" href="#">
                            <i class="fas fa-tools" aria-hidden="true"></i>
                            <span>@Back.Resources.Menu.Resource.Administration</span>
                        </a>

                        <ul class="nav nav-children">
                            <li class="nav-parent" id="menu-user">
                                <a class="nav-link" href="#">
                                    <i class="fas fa-user" aria-hidden="true"></i> <span>@Back.Resources.Menu.Resource.User</span> <span class="mega-sub-nav-toggle toggled float-right" data-toggle="collapse" data-target=".mega-sub-nav-sub-menu-1"></span>
                                </a>
                                <ul class="nav nav-children" style="">
                                    <li id="menu-user-list">
                                        <a class="nav-link" href="@Url.Action("Index", "User")">
                                            @Back.Resources.Menu.Resource.Users
                                        </a>
                                    </li>
                                    <li id="menu-user-new">
                                        <a class="nav-link" href="@Url.Action("Create", "User")">
                                            @Back.Resources.Menu.Resource.NewUser
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

    <script>
        // Maintain Scroll Position
        if (typeof localStorage !== 'undefined') {
            if (localStorage.getItem('sidebar-left-position') !== null) {
                var initialPosition = localStorage.getItem('sidebar-left-position'),
                    sidebarLeft = document.querySelector('#sidebar-left .nano-content');

                sidebarLeft.scrollTop = initialPosition;
            }
        }
    </script>
</aside>

Back/Views/Shared/_MenuUsuario.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    Layout = null;

}

<div id="userbox" class="userbox">
    <a href="#" data-toggle="dropdown">
        <figure class="profile-picture">
            <i class="fa fa-user"></i>
        </figure>

        <div class="profile-info custom-profile-info" data-lock-name="" data-lock-email="">
            <span class="name">@HttpContextAccessor.HttpContext.Session.GetString("username")</span>
        </div>

        <i class="fa custom-caret"></i>
    </a>

    <div class="dropdown-menu">
        <ul class="list-unstyled mb-2">
            <li class="divider"></li>

            <li>
                <a role="menuitem" tabindex="-1" href="@Url.Action("Logout", "Account")" class="text-truncate"><i class="bx bx-power-off"></i> @Back.Resources.Menu.Resource.Logout</a>
            </li>
        </ul>
    </div>
</div>

Back/Views/Shared/_SelectorIdioma.cshtml
@using Microsoft.AspNetCore.Builder;
@using Microsoft.AspNetCore.Localization;
@using Microsoft.AspNetCore.Mvc.Localization;
@using Microsoft.Extensions.Options;

@model dynamic
@{
    Layout = null;

}

<div id="userbox" class="userbox">
    <a href="#" data-toggle="dropdown">

        <div class="profile-info">
            <span class="name">@Back.Resources.Menu.Resource.Languages&nbsp;</span>
        </div>

        <i class="fa custom-caret"></i>
    </a>

    <div class="dropdown-menu">
        <ul class="list-unstyled mb-1">
            <li class="divider"></li>
            <li>
                @Html.ActionLink(Back.Resources.Language.Resource.Spanish, "ChangeLanguage", "Idiomas", new { @selectedLanguage = "es" })
            </li>
            <li>
                @Html.ActionLink(Back.Resources.Language.Resource.English, "ChangeLanguage", "Idiomas", new { @selectedLanguage = "en" })
            </li>
        </ul>
    </div>
</div>

Back/Views/User/Create.cshtml
@model Data.Models.User

@{
    ViewData["Title"] = Back.Resources.User.Resource.NewUser;
}

<form id="UserCreateForm" asp-action="Create" enctype="multipart/form-data">
    <div class="row">
        <div class="col-lg-12">
            <section class="card card-modern h-100">
                <header class="card-header">
                    <h2 class="card-title">@Back.Resources.User.Resource.NewUserData</h2>
                </header>
                <div class="card-body">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="validation-message">
                                <ul></ul>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-12">
                                    <div class="row">
                                        <label for="Username" class="col-sm-3 control-label pt-2">@Back.Resources.User.Resource.Username<span class="required">*</span></label>
                                        <div class="col-sm-9">
                                            <input asp-for="Username" class="form-control" autocomplete="new-text" required title="@Back.Resources.User.Resource.RequiredUsername">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-12">
                                    <div class="row">
                                        <label for="Password" class="col-sm-3 control-label pt-2">@Back.Resources.User.Resource.Password<span class="required">*</span></label>
                                        <div class="col-sm-9">
                                            <input asp-for="Password" type="password" class="form-control" autocomplete="new-text" required title="@Back.Resources.User.Resource.RequiredPassword">
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="form-group row">
                                <div class="col-lg-12">
                                    <div class="row">
                                        <div class="col-lg-5"></div>
                                        <input id="btnsubmit" type="button" class="btn btn-success col-lg-2" value="@Back.Resources.Actions.Resource.Save" />
                                        <div class="col-lg-5"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
</form>

@section Scripts {
    <script>

        // strings
        var strUserSaved = "@Back.Resources.User.Resource.UserSaved";
        var strSomethingWrong = "@Back.Resources.Actions.Resource.SomethingWrong";


        jQuery.validator.setDefaults({
            debug: true,
            success: "valid",
            ignore: []
        });

        var $summaryForm = $("#UserCreateForm");
        $summaryForm.validate({
            errorContainer: $summaryForm.find('div.validation-message'),
            errorLabelContainer: $summaryForm.find('div.validation-message ul'),
            wrapper: "li"
        });


        $("#btnsubmit").click(function () {
            if ($summaryForm.valid()) {
                var form = $('#UserCreateForm');
                var formData = new FormData(form[0]);

                $.ajax({
                    url: "@Url.Action("Create", "User")",
                    type: "POST",
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        Swal.fire({
                            title: strUserSaved,
                            icon: "success",
                        }).then((result) => {
                            if (result.isConfirmed) {
                                location.href = "@Url.Action("Index", "User")";
                            }
                        });
                    },
                    error: function (xhr, textStatus, errorThrown) {
                        Swal.fire({
                            title: strSomethingWrong,
                            icon: 'error'
                        });
                    }

                });
            }
        });

        $("#menu-administration").addClass("nav-expanded");
        $("#menu-administration").addClass("nav-active");
        $("#menu-user").addClass("nav-expanded");
        $("#menu-user").addClass("nav-active");
        $("#menu-user-new").addClass("nav-active");
    </script>
}